tasks:
  - init: echo "Replace me with a build script for the project."
    command:
      echo "Replace me with omething that should run on every start, or just
      remove me entirely."
image: gitpod/workspace-dotnet-vnc

vscode:
  extensions:
    - KishoreIthadi.dotnet-core-essentials@0.0.8:1KUSGmtAoru+QwfNslOZEQ==
    - ms-vscode.csharp@1.21.9:4NByVUcknHkm8M71U1BkDQ==
    - muhammad-sammy.csharp@1.23.2:c+VpGcfpxuc/M3ihERXCxA==
